version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn lerna:install
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy: 
    docker: 
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: mkdir ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: git fetch --tags
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn lerna:publish

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
              